model:
  # model path
  model_path: mobile_group8_hybrid_loss_fp32.onnx
  model_inputs: ["noisy_mag_5", "fb_h.1", "fb_c.1", "prev_fb_out_5"]
  model_outputs: ["fb_h", "fb_c", "new_fb_out_5", "model_out"]

feature_params:
  # sampling rate
  sampling_freq: 24000
  # window length
  frame_size_ms: 32
  # window hop length
  frame_stride_ms: 16
  # hamming or hanning
  window_type: hanning

inference:
  gpu: false
  engine_num_threads: 4
  # best_speed or best_quality
  model_type: best_speed

sound_processing:
  range_ctrl:
    sample_rate: 48000
    target_level_db: -3.0
    max_gain_db: 20
    attack_time: 0.0001
    release_time: 10
    hold_time: 3
  auto_gain_ctrl:
    target_level: 1
    max_gain: 20.0
    # sample_rate / 4
    average_len: 6000
    step_size_rise: 0.01
    step_size_fall: 0.01
  noise_gate_ctrl:
    sample_rate: 48000
    threshold: -40.0
    attack_time: 0.05
    release_time: 0.02
    hold_time: 0.05
  dynamic_range_compressor_ctrl:
    sample_rate: 48000
    threshold: -15.0
    ratio: 5
    knee_width: 0.0
    attack_time: 0.01
    release_time: 0.2
